[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Output directory for Next.js build
  publish = ".next"
  
  # Functions directory for Netlify Functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version for build
  NODE_VERSION = "18"
  
  # Next.js specific build optimizations
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Enable Next.js standalone output
  NEXT_PRIVATE_STANDALONE = "true"

# Redirect rules for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers for API endpoints
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/api/*"
  [headers.values]
    # Specific headers for API routes
    Cache-Control = "no-cache, no-store, must-revalidate"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    # Cache JavaScript files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Cache CSS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    # Cache images for 1 month
    Cache-Control = "public, max-age=2629746"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    # Cache images for 1 month
    Cache-Control = "public, max-age=2629746"

# Functions configuration
[functions]
  # Timeout for serverless functions (max 10 seconds on free tier)
  timeout = 10
  
  # Memory allocation for functions
  memory = 1024

# Development server configuration
[dev]
  command = "npm run dev"
  port = 3000
  publish = "."
  
  # Proxy API requests to local development server
  [[dev.redirects]]
    from = "/api/*"
    to = "http://localhost:3000/api/:splat"
    status = 200